### ISSUE TITLE
Incorrect syntax in devcontainer.json file for loading VSCode

### ISSUE THREAD

**Issue by yitao-zhou** [CSCI-GA-2820-SP23-001/promotions#2]
**Describe the bug**
VSCode has changed the way that extensions get loaded in the .devcontainers/devcontainer.json file. There is a missing line in between "customizations" and "extensions" to get VSCode loaded. 

**To Reproduce**
1. Go to VSCode
2. Click on starting with dev container
3. See error

**Expected behavior**
VSCode properly loaded a docker container for the project. 

**Observed behavior**
VSCode does not properly loaded a docker container. 

**Additional context**
The devcontainer.json file could be updated with the following:

{
    "name": "NYU Project",
    "dockerComposeFile": "docker-compose.yml",
    "service": "app",
    "workspaceFolder": "/app",
    "remoteUser": "vscode",
    "customizations": {
        "vscode": {
            "extensions": [
                "VisualStudioExptTeam.vscodeintellicode",
                "ms-python.python",
                "ms-python.pylint",
                "ms-python.vscode-pylance",
                "alexkrechik.cucumberautocomplete",
                "cstrap.flask-snippets",
                "yzhang.markdown-all-in-one",
                "bierner.github-markdown-preview",
                "hnw.vscode-auto-open-markdown-preview",
                "DavidAnson.vscode-markdownlint",
                "donjayamanne.githistory",
                "GitHub.vscode-pull-request-github",
                "hbenl.vscode-test-explorer",
                "LittleFoxTeam.vscode-python-test-adapter",
                "njpwerner.autodocstring",
                "redhat.vscode-yaml",
                "wholroyd.jinja",
                "Zignd.html-css-class-completion",
                "bbenoist.vagrant",
                "rangav.vscode-thunder-client",
                "ms-azuretools.vscode-docker",
                "ms-kubernetes-tools.vscode-kubernetes-tools",
                "streetsidesoftware.code-spell-checker"
            ]    
        },
    },
    "postCreateCommand": "sudo pip install -r requirements.txt",

    // Use 'forwardPorts' to make a list of ports inside the container available locally.
    // "forwardPorts": 8080,

    // Features to add to the dev container. More info: https://containers.dev/features.
    "features": {
        "ghcr.io/devcontainers/features/docker-in-docker:2": {},
        "ghcr.io/devcontainers/features/kubectl-helm-minikube:1": {}
    }
}

To Fix
Replace old JSON: https://github.com/CSCI-GA-2820-SP23-001/shopcarts/blob/master/.devcontainer/devcontainer.json
With updated JSON: https://github.com/nyu-devops/project-template/blob/master/.devcontainer/devcontainer.json

**Comment by gothmother** [comment]
@yitao-zhou changed story point from 1 to 3 per instructions "_Assign Story Points to all of the Stories in the first Sprint (stick with 3,5,8,13 = S,M,L,XL for now)_"
