### ISSUE TITLE
Create a schema in Flask framework for RESTful API calls

### ISSUE THREAD

**Issue by yitao-zhou** [CSCI-GA-2820-SP23-001/promotions#3]
**As a** Developer
**I need** starter code for RESTful APIs (CRUD and List)
**So that** I can add actions for each route 
   
 ### Details and Assumptions
We will be using Python with Flask
We need the RESTful API templates for holding each CRUD calls
   
 ### Acceptance Criteria  
 ```gherkin
Given the project is created in GitHub
When I issue a `git clone` on the project
Then I should get a Flask application with RESTful API starter code 
When I run `python server.py` and go to `localhost:5000/something`
Then I should see a template as it renders a template in GET HTTP method
```

**Comment by cdaid** [comment]
Per feedback, not needed as a user story
