### ISSUE TITLE
Create a PostgreSQL database to store promotion details

### ISSUE THREAD

**Issue by yitao-zhou** [CSCI-GA-2820-SP23-001/promotions#4]
**As a** developer
**I need** a database
**So that** record my promotion information inside the database
   
 ### Details and Assumptions
 Create a docker image for PostgreSQL in the docker-compose.yml file
 Set up an example row in the DB for a sample promotion
 The RESTful APIs can later read, update, create, and delete rows in the database
   
 ### Acceptance Criteria
   
 ```gherkin
 Given the cloned project from GitHub,
 When I run `python server.py` and go to `localhost:5432`
 I shall be able to see some information about the PostgreSQL
```

**Comment by cdaid** [comment]
Per feedback, not needed as a user story
