### ISSUE TITLE
Need the ability to Create a Promotion

### ISSUE THREAD

**Issue by Pimnipalmie** [CSCI-GA-2820-SP23-001/promotions#5]
**As a** Marketing Manager
**I need** the ability to create a promotion
**So that** I can add a new promotion and its details
   
 ### Details and Assumptions
 * The base URL would be /promotions/
 * Once created, the promotion will be visible on the e-commerce site
   
 ### Acceptance Criteria  
 ```

Given that the promotion `foo` never exists
When I issue `POST /promotions/foo`
Then the `foo` promotion should be created

When I issue `GET /promotions/foo`
Then I should see `foo` 

When I issue `GET /promotions`
Then I should see `foo` in the list of promotions 

```

**Comment by gothmother** [comment]
we can do two types of promotions: 
- x% off between date1 to date2
- buy a item(s) get b item(s) free

**Comment by cdaid** [comment]
I think it's important to consider what happens when creating a promotion? Does the end user need to include specific details like a promotion name/title, is there a timeframe for which the promotion is active, what are the details of the promotion?
