### ISSUE TITLE
Need the ability to Read a Promotion

### ISSUE THREAD

**Issue by Pimnipalmie** [CSCI-GA-2820-SP23-001/promotions#7]
**As an** Online Shopper
**I need** the ability to view a promotion
**So that** I can make purchase decisions accordingly
   
 ### Details and Assumptions
 * The base URL would be /promotions/
   
 ### Acceptance Criteria  

 ```
Given that the promotion `foo` exists
When I issue `GET /promotions`
Then I should see `foo` in the list of promotions

```

**Comment by cdaid** [comment]
This would be "GET" where data is pulled from the database to display/view
